# Generated by Django 5.1.1 on 2024-10-26 14:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Firm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('contact_number', models.CharField(max_length=12, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('website_url', models.URLField(blank=True, null=True, unique=True)),
                ('assistant_id', models.CharField(blank=True, max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('members', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
                ('root_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='firms', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('industry_type', models.IntegerField(choices=[(1, 'Trading'), (2, 'Manufacturing'), (3, 'Service'), (4, 'Others')])),
                ('entity_type', models.IntegerField(choices=[(1, 'HUF'), (2, 'Proprietary'), (3, 'Partnership'), (4, 'Corporation')])),
                ('gstin', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('pan_number', models.CharField(blank=True, max_length=10, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('zipcode', models.CharField(blank=True, max_length=20, null=True)),
                ('state', models.IntegerField(choices=[(1, 'Andhra Pradesh'), (2, 'Arunachal Pradesh '), (3, 'Assam'), (4, 'Bihar'), (5, 'Chhattisgarh'), (6, 'Goa'), (7, 'Gujarat'), (8, 'Haryana'), (9, 'Himachal Pradesh'), (10, 'Jammu and Kashmir '), (11, 'Jharkhand'), (12, 'Karnataka'), (13, 'Kerala'), (14, 'Madhya Pradesh'), (15, 'Maharashtra'), (16, 'Manipur'), (17, 'Meghalaya'), (18, 'Mizoram'), (19, 'Nagaland'), (20, 'Odisha'), (21, 'Punjab'), (22, 'Rajasthan'), (23, 'Sikkim'), (24, 'Tamil Nadu'), (25, 'Telangana'), (26, 'Tripura'), (27, 'Uttar Pradesh'), (28, 'Uttarakhand'), (29, 'West Bengal'), (30, 'Andaman and Nicobar Islands'), (31, 'Chandigarh'), (32, 'Dadra and Nagar Haveli'), (32, 'Daman and Diu'), (33, 'Lakshadweep'), (34, 'Delhi'), (35, 'Puducherry')])),
                ('mailing_address', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firms.firm')),
            ],
            options={
                'verbose_name_plural': 'Entities',
            },
        ),
    ]
