# Generated by Django 5.1.1 on 2024-10-17 10:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firms', '0004_alter_entity_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='books_beginning',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entity',
            name='fy_beginning',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
