# Generated by Django 5.1.1 on 2024-10-23 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firms', '0006_alter_entity_books_beginning_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entity',
            name='currency_type',
        ),
    ]
